/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatContainer: typeof import('./src/components/ChatContainer.vue')['default']
    ChatContent: typeof import('./src/components/ChatContent.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElText: typeof import('element-plus/es')['ElText']
    GptResView: typeof import('./src/components/GptResView.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
  }
}
